WORDS = ["Theme",
"Topic",
"Issue",
"Theory",
"Model",
"Principle",
"Aspect",
"Property",
"Feature",
"Characteristics",
"Characteristic",
"Characterize",
"Peculiarity",
"Peculiar",
"Specific ",
"Specifically",
"Unique",
"Common",
"Special",
"Specially",
"Particular particularly",
"Appropriate",
"Scope",
"Pattern",
"Sample",
"Way",
"Technique",
"Approach",
"Method",
"Methodology",
"Research",
"Study",
"Investigate",
"Investigation",
"Explore",
"Exploration",
"Analyse", 
"Analyze",
"Analysis ",
"Examine",
"Examination",
"Consider",
"Consideration",
"Considerable considerably",
"Account",
"Perspective",
"Prospect",
"Case",
"View",
"Significance",
"Significant",
"Insignificance",
"Insignificant",
"Essential essentially",
"Important",
"Current",
"Burning",
"Topical",
"Modern",
"Up-to-date",
"State-of-the-art",
"General",
"Generally",
"Identify ",
"Identification",
"Assess",
"Assessment",
"Estimate",
"Estimation",
"Discuss",
"Discussion ",
"Illustrate",
"Illustration",
"Demonstrate",
"Demonstration",
"Show",
"Exhibit",
"Perform",
"Performance",
"Carry out",
"Conduct",
"Calculate",
"Calculation",
"Compute",
"Computation",
"Measure",
"Measurement",
"Weigh",
"Weight",
"Derive",
"Derivation",
"Equal",
"Equation",
"Assume",
"Assumption",
"Find ",
"Findings",
"Support",
"Challenge",
"Provide",
"Provision",
"Affect",
"Effect",
"Include",
"Inclusion",
"Involve",
"Exclude",
"Exclusion",
"Develop",
"Development",
"Design",
"Classify",
"Classification",
"Establish",
"Establishment",
"Present",
"Presentation",
"Attempt",
"Explain",
"Explanation",
"Emphasise",
"Emphasize",
"Emphasis",
"Thesis",
"Hypothesis",
"Describe",
"Description",
"Relative",
"Relatively",
"Relevant",
"Abstract",
"Concrete",
"Complex",
"Quantitative",
"Qualitative",
"Accurate",
"Inaccurate",
"Rough",
"Roughly",
"Approximate",
"Approximation",
"Approximately",
"Precise",
"Precisely",
"Precision",
"Exactly",
"Apparent",
"Potential",
"Principal",
"Rigorous",
"Comparative", 
"Comparatively",
"Especially",
"Primary", 
"Primarily",
"Mainly",
"Mostly",
"Largely",
"Direct", 
"Directly",
"Indirect", 
"Indirectly",
"Frequent", 
"Frequently",
"Eventually",
"Ultimate", 
"Ultimately",
"Merely",
"Hardly ever",
"Possible", 
"Possibly",
"Probable", 
"Probably",
"Basically",
"Put forward",
"Make up", 
"Made up",
"Point out",
"Point up",
"Set out",
"Go into",
"Go through",
"Amount",
"Number",
"Substantial",
"Substantially",
"Deal with",
"Devoted to",
"Concern",
"Concerning",
"Few",
"A few",
"Little",
"A little",
"Occur",
"Occurrence",
"Refer to",
"Reference",
"Shed light on",
"In light of",
"Highlight",
"Crucial",
"Decisive",
"Sufficient",
"Preliminary",
"Preliminarily",
"Comprehensive",
"Comprehensively",
"Convenient",
"Contribute",
"Contribution",
"Evidence",
"Suggest",
"Propose",
"Offer",
"A great deal of",
"A wide range of",
"To … (some) extent",
"In a variety of ways",
"Aim",
"Purpose",
"Goal",
"Objective",
"Intend",
"In terms of",
"With respect to",
"With regard to",
"In respect of",
"Outline",
"Summary",
"Summarize",
"Obtain",
"Determine",
"Produce",
"Production",
"Create",
"Creation",
"Make use of",
"Extensive",
"Extensively",
"Careful",
"Carefully",
"Detailed",
"In detail",
"Thorough",
"Thoroughly",
"Remarkable",
"Striking",
"Consist in",
"Consist of",
"Contain",
"Comprise",
"Yield",
"Generate",
"Allow",
"Enable",
"Ensure",
"Permit",
"Modify", 
"Modification",
"Alter", 
"Alteration",
"Enhance", 
"Enhancement",
"Similar", 
"Similarly",
"Similarity ",
"Verify", 
"Verification",
"While",
"Whereas",
# "Since (=as)",
# "For (=as)",
"Initially",
"Finally",
"Following",
"Subsequently",
"Although",
"Despite",
"In spite of",
"Instead (of)",
"Nevertheless",
"On the contrary",
"In contrast",
"By contrast",
"On the one hand, on the other hand",
"Furthermore",
"Moreover",
"Due to",
"In order to",
"Hence",
"Therefore",
"Provided that",
"Unless",
]

WORDS = ['Theme', 'Topic', 'Issue', 'Theory', 'Model', 'Aspect', 'Property', 'Characteristics', 'Characteristic', 'Characterize', 'Peculiarity', 'Peculiar', 'Specific ', 'Specifically', 'Unique', 'Specially', 'Particular particularly', 'Scope', 'Pattern', 'Methodology', 'Study', 'Investigate', 'Investigation', 'Explore', 'Exploration', 'Analyse', 'Analysis ', 'Examine', 'Examination', 'Consider', 'Consideration', 'Considerable considerably', 'Account', 'Perspective', 'Prospect', 'View', 'Significance', 'Significant', 'Insignificance', 'Insignificant', 'Essential essentially', 'Burning', 'Topical', 'Modern', 'Up-to-date', 'Generally', 'Identify ', 'Identification', 'Assess', 'Assessment', 'Discussion ', 'Illustrate', 'Illustration', 'Demonstrate', 'Demonstration', 'Exhibit', 'Carry out', 'Calculate', 'Calculation', 'Compute', 'Computation', 'Weigh', 'Weight', 'Derive', 'Derivation', 'Equation', 'Assumption', 'Find ', 'Findings', 'Support', 'Challenge', 'Provision', 'Inclusion', 'Involve', 'Exclude', 'Exclusion', 'Develop', 'Classification', 'Establish', 'Establishment', 'Present', 'Presentation', 'Attempt', 'Explanation', 'Emphasise', 'Emphasis', 'Thesis', 'Hypothesis', 'Describe', 'Concrete', 'Complex', 'Qualitative', 'Accurate', 'Inaccurate', 'Rough', 'Roughly', 'Approximate', 'Approximately', 'Precisely', 'Exactly', 'Apparent', 'Potential', 'Principal', 'Rigorous', 'Comparative', 'Comparatively', 'Primary', 'Primarily', 'Largely', 'Indirectly', 'Frequent', 'Eventually', 'Ultimate', 'Merely', 'Hardly ever', 'Possible', 'Possibly', 'Probable', 'Probably', 'Basically', 'Put forward', 'Make up', 'Made up', 'Point out', 'Point up', 'Set out', 'Go into', 'Go through', 'Amount', 'Substantial', 'Substantially', 'Deal with', 'Devoted to', 'Concerning', 'A few', 'Little', 'A little', 'Occurrence', 'Shed light on', 'In light of', 'Highlight', 'Decisive', 'Sufficient', 'Preliminary', 'Preliminarily', 'Comprehensive', 'Comprehensively', 'Convenient', 'Contribution', 'Evidence', 'Suggest', 'Offer', 'A great deal of', 'A wide range of', 'To … (some) extent', 'In a variety of ways', 'Purpose', 'Objective', 'Intend', 'In terms of', 'With regard to', 'In respect of', 'Summarize', 'Produce', 'Production', 'Create', 'Creation', 'Make use of', 'Extensive', 'Extensively', 'Careful', 'Detailed', 'Thorough', 'Thoroughly', 'Striking', 'Consist in', 'Consist of', 'Contain', 'Comprise', 'Allow', 'Permit', 'Modify', 'Modification', 'Alter', 'Alteration', 'Similarly', 'Similarity ', 'Verification', 'Whereas', 'Finally', 'Subsequently', 'Although', 'Despite', 'In spite of', 'Nevertheless', 'On the contrary', 'In contrast', 'By contrast', 'On the one hand, on the other hand', 'Furthermore', 'Moreover', 'Provided that']